name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build for macOS (arm64)
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -trimpath -a -o ./build/snake ./cmd/main.go
          chmod +x ./build/snake
          zip -j ./build/snake-macos.zip ./build/snake

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-binaries
          path: ./build/snake-macos.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build for Windows (amd64)
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          go build -trimpath -a -o ./build/snake.exe ./cmd/main.go
          Compress-Archive -Path ./build/snake.exe -DestinationPath ./build/snake-windows.zip

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-binaries
          path: ./build/snake-windows.zip

  release:
    needs: [ build-macos, build-windows ]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v8
        with:
          name: macos-binaries
          path: ./build

      - name: Download Windows artifacts
        uses: actions/download-artifact@v8
        with:
          name: windows-binaries
          path: ./build

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./build/snake-macos.zip
            ./build/snake-windows.zip
          generate_release_notes: true
