name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build for macOS (arm64)
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -trimpath -a -o ./build/snake ./cmd/main.go

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: ./build/snake

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build for Windows (amd64)
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -trimpath -a -o ./build/snake.exe ./cmd/main.go

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: ./build/snake.exe

  release:
    needs: [ build-macos, build-windows ]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-binaries
          path: ./build

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-binaries
          path: ./build

      - name: Set executable permission
        run: chmod +x ./build/snake

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/snake
            ./build/snake.exe
          generate_release_notes: true
